format_version: v1.0
type: GeneratorComponent
attributes: {id: sys_console}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_CONSOLE_USB_CONNECTION_COUNTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_console, value: '2'}
  - type: Integer
    attributes: {id: SYS_CONSOLE_USB_READ_WRITE_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_console, value: '64'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: sys_console}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: USB_DEVICE_CDC_0}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: '0'}
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE_SET}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: USB_CDC}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_USB_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console, value: '0'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_RX_BUFFER_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_TX_BUFFER_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: User
            attributes: {value: '256'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_CDC_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: SYS_CONSOLE_USB_DEVICE_SPEED}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_0, value: Full Speed}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: sys_console_USB_DEVICE_CDC_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_device_cdc_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USB Device}
  - type: InstanceComponent
    attributes: {instance: '1', id: sys_console}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: USB_DEVICE_CDC_1}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: '1'}
      - type: String
        attributes: {id: SYS_CONSOLE_DEVICE_SET}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: USB_CDC}
      - type: Integer
        attributes: {id: SYS_CONSOLE_DEVICE_USB_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console, value: '1'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_RX_BUFFER_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Integer
        attributes: {id: SYS_CONSOLE_TX_BUFFER_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: User
            attributes: {value: '256'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_UART_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_CDC_SOURCE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_DEFINITIONS_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: SYS_CONSOLE_USB_DEVICE_SPEED}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: sys_console_1, value: Full Speed}
      - type: File
        attributes: {id: SYS_CONSOLE_USB_HEADER}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: sys_console_USB_DEVICE_CDC_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_device_cdc_1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USB Device}
- type: ElementPosition
  attributes: {x: '480', y: '94', id: sys_console}
