files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8E6E4893125920C25696936C33DBF3E4
  logicalPath: config/pic32mx470_curiosity/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8E6E4893125920C25696936C33DBF3E4
- generatedChecksum: F95D354CF700B247BF6F0F01B6353452
  logicalPath: config/pic32mx470_curiosity/driver/usart
  name: drv_usart.c
  physicalPath: driver/usart/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F95D354CF700B247BF6F0F01B6353452
- generatedChecksum: 872B12305821887C9AFF78A64839A20D
  logicalPath: config/pic32mx470_curiosity/driver/usart
  name: drv_usart_local.h
  physicalPath: driver/usart/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 872B12305821887C9AFF78A64839A20D
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: 3F7F2F5A9045DAB680A168E3155CD871
  logicalPath: config/pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3F7F2F5A9045DAB680A168E3155CD871
- generatedChecksum: A07722F4CCC78487AA451429B00B25F7
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A07722F4CCC78487AA451429B00B25F7
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: E78B3EC1DDDC45026163CEB430466288
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: E78B3EC1DDDC45026163CEB430466288
- generatedChecksum: 43ED69BFF527457A535E74C5F35085AE
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 43ED69BFF527457A535E74C5F35085AE
- generatedChecksum: F98EA3A2B4A824E463067984A966A761
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: F98EA3A2B4A824E463067984A966A761
- generatedChecksum: 59D729DE48A4419BEEC44F6BC581282C
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 59D729DE48A4419BEEC44F6BC581282C
- generatedChecksum: 0A6893369C4DA0EE7906866EB6E1D310
  logicalPath: config/pic32mx470_curiosity/system/dma
  name: sys_dma.c
  physicalPath: system/dma
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0A6893369C4DA0EE7906866EB6E1D310
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mx470_curiosity/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mx470_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mx470_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 3AD9B94DC2D509696331D0EA0B4CFD37
  logicalPath: config/pic32mx470_curiosity/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3AD9B94DC2D509696331D0EA0B4CFD37
- generatedChecksum: 5C202CE15C6412BDE8768DF5088F7EA1
  logicalPath: config/pic32mx470_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5C202CE15C6412BDE8768DF5088F7EA1
- generatedChecksum: 1827E017E2296FAC1B196483483B3C8A
  logicalPath: config/pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1827E017E2296FAC1B196483483B3C8A
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mx470_curiosity/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mx470_curiosity/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 32A69D3A36D95B996CA22CB89C5907DB
  logicalPath: config/pic32mx470_curiosity/driver/usart
  name: drv_usart.h
  physicalPath: driver/usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 32A69D3A36D95B996CA22CB89C5907DB
- generatedChecksum: 6A33BD761891FC1DA0DA3D6899CD645F
  logicalPath: config/pic32mx470_curiosity/driver/usart
  name: drv_usart_definitions.h
  physicalPath: driver/usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 6A33BD761891FC1DA0DA3D6899CD645F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mx470_curiosity/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mx470_curiosity/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mx470_curiosity/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
- generatedChecksum: 041902C758A6026B53089B38D2C8EDE6
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 041902C758A6026B53089B38D2C8EDE6
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mx470_curiosity/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: C6D4E4697C914BC63255859D937D2F36
  logicalPath: config/pic32mx470_curiosity/system/dma
  name: sys_dma.h
  physicalPath: system/dma
  security: NON_SECURE
  type: HEADER
  userChecksum: C6D4E4697C914BC63255859D937D2F36
- generatedChecksum: 42E557EFE638D7A736FB88AA84F085F1
  logicalPath: config/pic32mx470_curiosity/system/dma
  name: sys_dma_mapping.h
  physicalPath: system/dma
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E557EFE638D7A736FB88AA84F085F1
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mx470_curiosity/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mx470_curiosity/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mx470_curiosity/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mx470_curiosity/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mx470_curiosity/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mx470_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 52AA20E8BAA488B3B6581379249C0FCE
  logicalPath: config/pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 52AA20E8BAA488B3B6581379249C0FCE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
