format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: drv_memory_0, targetAttachmentID: drv_media}
- type: ElementPosition
  attributes: {x: '295', y: '149', id: sys_fs}
