format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MX274_XLP_Starter_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '30', y: '60', id: BSP_PIC32MX274_XLP_Starter_Kit}
