files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8E6E4893125920C25696936C33DBF3E4
  logicalPath: config/pic32mx470_curiosity/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8E6E4893125920C25696936C33DBF3E4
- generatedChecksum: 4F1E691F70878F4E114F5C6BDB4BD606
  logicalPath: config/pic32mx470_curiosity/system/fs/fat_fs/hardware_access
  name: diskio.c
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4F1E691F70878F4E114F5C6BDB4BD606
- generatedChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
- generatedChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory_file_system.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
- generatedChecksum: DC6BF3BD3BE8D60070E6CFAD73ECC6EF
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory_nvm.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC6BF3BD3BE8D60070E6CFAD73ECC6EF
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: D991CF8C9FF9C5452F5D78B4D7BC766E
  logicalPath: config/pic32mx470_curiosity/system/fs/fat_fs/file_system
  name: ff.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: D991CF8C9FF9C5452F5D78B4D7BC766E
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config/pic32mx470_curiosity/system/fs/fat_fs/file_system
  name: ffunicode.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: 87FE13D195AB4A7416907260204B0254
  logicalPath: config/pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 87FE13D195AB4A7416907260204B0254
- generatedChecksum: 6FBA0EE668AAD1ECC00EDDD4EE98FA06
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6FBA0EE668AAD1ECC00EDDD4EE98FA06
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: E238A59DA23D1B82E4DD27EB3A9430BA
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: E238A59DA23D1B82E4DD27EB3A9430BA
- generatedChecksum: 74D0B30594C95648D731CA732B85977B
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 74D0B30594C95648D731CA732B85977B
- generatedChecksum: ED56F201A2931EB315CDA020E8D3ADAE
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED56F201A2931EB315CDA020E8D3ADAE
- generatedChecksum: E298DB11D075A4B331FE19805EAB45D5
  logicalPath: config/pic32mx470_curiosity/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: E298DB11D075A4B331FE19805EAB45D5
- generatedChecksum: 64197587C5A197FD05E94AB039A2DD66
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64197587C5A197FD05E94AB039A2DD66
- generatedChecksum: 1F79CD9E378D98E657FCEB0552B2B659
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs_fat_interface.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F79CD9E378D98E657FCEB0552B2B659
- generatedChecksum: 8A608E11F4981AA9CC52EA5EF5C76F4A
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs_media_manager.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A608E11F4981AA9CC52EA5EF5C76F4A
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mx470_curiosity/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 22CA1BA8315F3E404A8BD8B5BD0C04CF
  logicalPath: config/pic32mx470_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 22CA1BA8315F3E404A8BD8B5BD0C04CF
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mx470_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 3AD9B94DC2D509696331D0EA0B4CFD37
  logicalPath: config/pic32mx470_curiosity/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3AD9B94DC2D509696331D0EA0B4CFD37
- generatedChecksum: 56F58C593C32E87DE4F3AE3F288E1DEE
  logicalPath: config/pic32mx470_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 56F58C593C32E87DE4F3AE3F288E1DEE
- generatedChecksum: AC0DFF6597704CBD55F359610BC1A2ED
  logicalPath: config/pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: AC0DFF6597704CBD55F359610BC1A2ED
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config/pic32mx470_curiosity/system/fs/fat_fs/hardware_access
  name: diskio.h
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mx470_curiosity/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mx470_curiosity/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 64EA07D284832B8E56C403AE90B52CD5
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: 64EA07D284832B8E56C403AE90B52CD5
- generatedChecksum: B37635A7E5516B08B10146BB58A6C2D9
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory_definitions.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: B37635A7E5516B08B10146BB58A6C2D9
- generatedChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory_local.h
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
- generatedChecksum: D7B4ABDE58DE140171E13AF1B3C3292A
  logicalPath: config/pic32mx470_curiosity/driver/memory
  name: drv_memory_nvm.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: D7B4ABDE58DE140171E13AF1B3C3292A
- generatedChecksum: 187EFA39553617C34D670BFA3AA15C5F
  logicalPath: config/pic32mx470_curiosity/system/fs/fat_fs/file_system
  name: ff.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 187EFA39553617C34D670BFA3AA15C5F
- generatedChecksum: 6E11D27FFFCF7C7BB6AE5B10AD60786C
  logicalPath: config/pic32mx470_curiosity/system/fs/fat_fs/file_system
  name: ffconf.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 6E11D27FFFCF7C7BB6AE5B10AD60786C
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mx470_curiosity/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mx470_curiosity/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mx470_curiosity/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
- generatedChecksum: A7741B1B3001372A5CC20C88BB99A8CF
  logicalPath: config/pic32mx470_curiosity/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: A7741B1B3001372A5CC20C88BB99A8CF
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mx470_curiosity/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: 64F22D21B48A241C02F4D9DEB576D5B6
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 64F22D21B48A241C02F4D9DEB576D5B6
- generatedChecksum: 0D9FE9035E3AA8082C5657240106F2DC
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs_fat_interface.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D9FE9035E3AA8082C5657240106F2DC
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: C57A4CE87A00A891A99A4248ADEE0D2E
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs_media_manager.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: C57A4CE87A00A891A99A4248ADEE0D2E
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config/pic32mx470_curiosity/system/fs
  name: sys_fs_media_manager_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mx470_curiosity/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mx470_curiosity/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mx470_curiosity/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mx470_curiosity/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config/pic32mx470_curiosity/system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mx470_curiosity/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mx470_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 52AA20E8BAA488B3B6581379249C0FCE
  logicalPath: config/pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 52AA20E8BAA488B3B6581379249C0FCE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mx470_curiosity/system/fs/fat_fs/file_system;../src/config/pic32mx470_curiosity/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mx470_curiosity/system/fs/fat_fs/file_system;../src/config/pic32mx470_curiosity/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
