files:
- generatedChecksum: F58DB2348A0FCE945652B285010E5F8A
  logicalPath: FreeRTOS\Source
  name: FreeRTOS_tasks.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: F58DB2348A0FCE945652B285010E5F8A
- generatedChecksum: ''
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: ''
- generatedChecksum: ''
  logicalPath: ''
  name: app1.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: ''
- generatedChecksum: ''
  logicalPath: ''
  name: app2.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: ''
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config\pic32mx_eth_sk2\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: 8ACE0DEBD82F6829438A4674565451FB
  logicalPath: FreeRTOS\Source
  name: croutine.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8ACE0DEBD82F6829438A4674565451FB
- generatedChecksum: B3B5445B14BD9B6A35F1C5B995C9BBF7
  logicalPath: FreeRTOS\Source
  name: event_groups.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: B3B5445B14BD9B6A35F1C5B995C9BBF7
- generatedChecksum: EC410AF32A00CC5E9DF0F879297B47F1
  logicalPath: config\pic32mx_eth_sk2
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC410AF32A00CC5E9DF0F879297B47F1
- generatedChecksum: B7DBFD6F500AAD4713403E985EB18EAE
  logicalPath: config\pic32mx_eth_sk2
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B7DBFD6F500AAD4713403E985EB18EAE
- generatedChecksum: 972E955D94A63BA89BF6ABD6AADB1023
  logicalPath: FreeRTOS\Source\portable\MemMang
  name: heap_1.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 972E955D94A63BA89BF6ABD6AADB1023
- generatedChecksum: CAB273C25C9507152201F20CD72D94F2
  logicalPath: config\pic32mx_eth_sk2
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CAB273C25C9507152201F20CD72D94F2
- generatedChecksum: 21AC72888CC2AFF8195C6ACBD940F642
  logicalPath: config\pic32mx_eth_sk2
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 21AC72888CC2AFF8195C6ACBD940F642
- generatedChecksum: 2335C329F2EAF94F702818F1429DB49A
  logicalPath: config\pic32mx_eth_sk2
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2335C329F2EAF94F702818F1429DB49A
- generatedChecksum: 3FEE521CEF14928AE38E7FA9BF6D75E6
  logicalPath: FreeRTOS\Source
  name: list.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3FEE521CEF14928AE38E7FA9BF6D75E6
- generatedChecksum: ''
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: ''
- generatedChecksum: 13F747CBE45AD5A7C4DF007FEA796CC9
  logicalPath: config\pic32mx_eth_sk2\osal
  name: osal_freertos.c
  physicalPath: osal
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13F747CBE45AD5A7C4DF007FEA796CC9
- generatedChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
  logicalPath: config\pic32mx_eth_sk2\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
- generatedChecksum: 9573245AA1016A26B9522406787F6F58
  logicalPath: config\pic32mx_eth_sk2\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9573245AA1016A26B9522406787F6F58
- generatedChecksum: 78A177A29C2783D974A8670949C03300
  logicalPath: config\pic32mx_eth_sk2\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78A177A29C2783D974A8670949C03300
- generatedChecksum: E57AF2580EA0FD297CA3B4730328A18A
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MX
  name: port.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MX
  security: NON_SECURE
  type: SOURCE
  userChecksum: E57AF2580EA0FD297CA3B4730328A18A
- generatedChecksum: C95582D7E657BFC5C1AB7971E1B463DB
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MX
  name: port_asm.S
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MX
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95582D7E657BFC5C1AB7971E1B463DB
- generatedChecksum: 09041728D74A4E3A32C7D4EAA96C4EE7
  logicalPath: FreeRTOS\Source
  name: queue.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 09041728D74A4E3A32C7D4EAA96C4EE7
- generatedChecksum: D6CF30BDCE1A813D9ACF3905EBD6A871
  logicalPath: FreeRTOS\Source
  name: stream_buffer.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: D6CF30BDCE1A813D9ACF3905EBD6A871
- generatedChecksum: 7FED81813390B4EF70CFCA6941211A60
  logicalPath: config\pic32mx_eth_sk2
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7FED81813390B4EF70CFCA6941211A60
- generatedChecksum: F1B86F6E1527FD59A8713B67564F2898
  logicalPath: FreeRTOS\Source
  name: timers.c
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: F1B86F6E1527FD59A8713B67564F2898
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\pic32mx_eth_sk2\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: AF3A8D8AA610E7DFD3E38DDAC5E42074
  logicalPath: FreeRTOS\Source\include
  name: FreeRTOS.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: AF3A8D8AA610E7DFD3E38DDAC5E42074
- generatedChecksum: 3D95199172141CFC5CBBBEF2C978DF4D
  logicalPath: config\pic32mx_eth_sk2
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D95199172141CFC5CBBBEF2C978DF4D
- generatedChecksum: CEF74FD3B70DA42045EB71BC81B5FACF
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MX
  name: ISR_Support.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MX
  security: NON_SECURE
  type: HEADER
  userChecksum: CEF74FD3B70DA42045EB71BC81B5FACF
- generatedChecksum: ''
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: ''
- generatedChecksum: ''
  logicalPath: ''
  name: app1.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: ''
- generatedChecksum: ''
  logicalPath: ''
  name: app2.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: ''
- generatedChecksum: 91DEF69BECBD431E7EDDC04D3B113000
  logicalPath: config\pic32mx_eth_sk2\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 91DEF69BECBD431E7EDDC04D3B113000
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config\pic32mx_eth_sk2
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: 48B661D8C967C6BC397001F10FB43D1D
  logicalPath: FreeRTOS\Source\include
  name: croutine.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 48B661D8C967C6BC397001F10FB43D1D
- generatedChecksum: A9D7A0B7466B2668B7C2C80C09BF77D1
  logicalPath: config\pic32mx_eth_sk2
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A9D7A0B7466B2668B7C2C80C09BF77D1
- generatedChecksum: 1EA4EDD5EA90F43EC407DE32441159A9
  logicalPath: FreeRTOS\Source\include
  name: deprecated_definitions.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 1EA4EDD5EA90F43EC407DE32441159A9
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\pic32mx_eth_sk2
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: B1D1D455E111FA70C46AD40562D78CE2
  logicalPath: FreeRTOS\Source\include
  name: event_groups.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: B1D1D455E111FA70C46AD40562D78CE2
- generatedChecksum: FE17D325A06479D956285C5438994B83
  logicalPath: FreeRTOS\Source\include
  name: list.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: FE17D325A06479D956285C5438994B83
- generatedChecksum: DDE2C9D46642D120A0202AC851E1A777
  logicalPath: FreeRTOS\Source\include
  name: message_buffer.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: DDE2C9D46642D120A0202AC851E1A777
- generatedChecksum: 2D674B8B1FCF07504AF90FA5CE2F9A23
  logicalPath: FreeRTOS\Source\include
  name: mpu_prototypes.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D674B8B1FCF07504AF90FA5CE2F9A23
- generatedChecksum: 953D372D8F7991D4F86AD4ABD42AE4CE
  logicalPath: FreeRTOS\Source\include
  name: mpu_wrappers.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 953D372D8F7991D4F86AD4ABD42AE4CE
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mx_eth_sk2\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 167A43EFF8A31441EBF85AC77958A30B
  logicalPath: config\pic32mx_eth_sk2\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 167A43EFF8A31441EBF85AC77958A30B
- generatedChecksum: EDB1F623D39C14DC72E68558DB41B57B
  logicalPath: config\pic32mx_eth_sk2\osal
  name: osal_freertos.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: EDB1F623D39C14DC72E68558DB41B57B
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_eth_sk2\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 1BA4A111238723BF8148CF1BC7442A3C
  logicalPath: config\pic32mx_eth_sk2\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 1BA4A111238723BF8148CF1BC7442A3C
- generatedChecksum: 54B6A0896A14D84BEC8A585701BD86DC
  logicalPath: config\pic32mx_eth_sk2\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 54B6A0896A14D84BEC8A585701BD86DC
- generatedChecksum: 5A686FF678CBFBB4A1FEB86B66DCEC98
  logicalPath: FreeRTOS\Source\include
  name: portable.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A686FF678CBFBB4A1FEB86B66DCEC98
- generatedChecksum: 4B3C9E3866058CD9D3336DC57E0A7007
  logicalPath: FreeRTOS\Source\portable\MPLAB\PIC32MX
  name: portmacro.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\portable\MPLAB\PIC32MX
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B3C9E3866058CD9D3336DC57E0A7007
- generatedChecksum: 696F66B2428CC530389C53B5FE617CE1
  logicalPath: FreeRTOS\Source\include
  name: projdefs.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 696F66B2428CC530389C53B5FE617CE1
- generatedChecksum: 6CB1FF8C27E6755C63D75369D1D7A37A
  logicalPath: FreeRTOS\Source\include
  name: queue.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 6CB1FF8C27E6755C63D75369D1D7A37A
- generatedChecksum: 9F1AE7D29D09ED8CC21F3DA08049FB79
  logicalPath: FreeRTOS\Source\include
  name: semphr.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F1AE7D29D09ED8CC21F3DA08049FB79
- generatedChecksum: D0D11C3D2D1BD585018AE271E1AC3B8F
  logicalPath: FreeRTOS\Source\include
  name: stack_macros.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: D0D11C3D2D1BD585018AE271E1AC3B8F
- generatedChecksum: 7C71A9D2BEF16AC21C17ED5C2452C263
  logicalPath: FreeRTOS\Source\include
  name: stream_buffer.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 7C71A9D2BEF16AC21C17ED5C2452C263
- generatedChecksum: 84B3224817BDD8B37961BB3B3441E134
  logicalPath: FreeRTOS\Source\include
  name: task.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: 84B3224817BDD8B37961BB3B3441E134
- generatedChecksum: C8BB70E2423A57902E9FDC0C9EC81F8D
  logicalPath: FreeRTOS\Source\include
  name: timers.h
  physicalPath: ..\..\third_party\rtos\FreeRTOS\Source\include
  security: NON_SECURE
  type: HEADER
  userChecksum: C8BB70E2423A57902E9FDC0C9EC81F8D
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_eth_sk2
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: ''
  logicalPath: config\pic32mx_eth_sk2
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: ''
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_eth_sk2;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mx_eth_sk2;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mx_eth_sk2;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MX;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_eth_sk2;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
