format_version: v1.0
type: UniqueComponent
attributes: {id: drv_at25}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DRV_AT25_CHIP_SELECT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '21'}
  - type: KeyValueSet
    attributes: {id: DRV_AT25_HOLD_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '24'}
  - type: String
    attributes: {id: DRV_AT25_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_at25, value: SPI1}
  - type: KeyValueSet
    attributes: {id: DRV_AT25_WRITE_PROTECT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_at25_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: spi1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI1_SPI}
- type: ElementPosition
  attributes: {x: '247', y: '93', id: drv_at25}
