files:
- generatedChecksum: E05F8B7AAAC08B119E65E4EBD046E8A6
  logicalPath: ''
  name: app1.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: E05F8B7AAAC08B119E65E4EBD046E8A6
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config\pic32mx_sk\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: EC410AF32A00CC5E9DF0F879297B47F1
  logicalPath: config\pic32mx_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC410AF32A00CC5E9DF0F879297B47F1
- generatedChecksum: 73F195B04537400A2CDFBCC611CB0830
  logicalPath: config\pic32mx_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 73F195B04537400A2CDFBCC611CB0830
- generatedChecksum: 74E1A72B5AE328C213F9F1B28B184B64
  logicalPath: config\pic32mx_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 74E1A72B5AE328C213F9F1B28B184B64
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
  logicalPath: config\pic32mx_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: \peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9854678C3A3E4E9544EC7450ACBAE52A
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config\pic32mx_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: \peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 304E7E3E9D6E957D6C2DFF4AB8C23F91
  logicalPath: config\pic32mx_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: \peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 304E7E3E9D6E957D6C2DFF4AB8C23F91
- generatedChecksum: 78A177A29C2783D974A8670949C03300
  logicalPath: config\pic32mx_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: \peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 78A177A29C2783D974A8670949C03300
- generatedChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
  logicalPath: config\pic32mx_sk\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
- generatedChecksum: 40A99C84F50EB7DFAA579B8675F140DD
  logicalPath: config\pic32mx_sk\system\time
  name: sys_time.c
  physicalPath: system\time\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 40A99C84F50EB7DFAA579B8675F140DD
- generatedChecksum: C16545B1C4C549AD3DED58E0A085AC2E
  logicalPath: config\pic32mx_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C16545B1C4C549AD3DED58E0A085AC2E
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\pic32mx_sk\stdio
  name: xc32_monitor.c
  physicalPath: \stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: null
  logicalPath: ''
  name: app1.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 91DEF69BECBD431E7EDDC04D3B113000
  logicalPath: config\pic32mx_sk\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 91DEF69BECBD431E7EDDC04D3B113000
- generatedChecksum: 27052825275EAFEFC206EB6C14A6E3EB
  logicalPath: config\pic32mx_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 27052825275EAFEFC206EB6C14A6E3EB
- generatedChecksum: 19821B44E219739618FC114FD4E47B30
  logicalPath: config\pic32mx_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 19821B44E219739618FC114FD4E47B30
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\pic32mx_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mx_sk\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mx_sk\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B358678B02AC7D3AD6CC80621ECC826D
  logicalPath: config\pic32mx_sk\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B358678B02AC7D3AD6CC80621ECC826D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: \peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 2712EE363EC8AC102002609F5B5F3DCF
  logicalPath: config\pic32mx_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: \peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 2712EE363EC8AC102002609F5B5F3DCF
- generatedChecksum: F443860EB4D37FBF486C176F7DDAC101
  logicalPath: config\pic32mx_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: \peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F443860EB4D37FBF486C176F7DDAC101
- generatedChecksum: B9AB932B9BA0D0B8E4731B0752B3F9C5
  logicalPath: config\pic32mx_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: \peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: B9AB932B9BA0D0B8E4731B0752B3F9C5
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mx_sk\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mx_sk\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mx_sk\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config\pic32mx_sk\system\time
  name: sys_time.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 82C87C4CF49EE4D859363C15E9073333
  logicalPath: config\pic32mx_sk\system\time
  name: sys_time_definitions.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 82C87C4CF49EE4D859363C15E9073333
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config\pic32mx_sk\system\time
  name: sys_time_local.h
  physicalPath: system\time\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mx_sk\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mx_sk\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mx_sk\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config\pic32mx_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 133C9651E2D22B4E46B149A3252D80D3
  logicalPath: config\pic32mx_sk
  name: p32MX360F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 133C9651E2D22B4E46B149A3252D80D3
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;../src/packs/PIC32MX360F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;../src/packs/PIC32MX360F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
