configName: pic32mx_eth_sk2
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32MX795F512L
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bootloader_apps_uart;bsp;core;core_apps_pic32cm_mc00;core_apps_pic32mk;core_apps_pic32mx;core_apps_pic32mz_da;core_apps_pic32mz_ef;core_apps_pic32mz_w1;core_apps_sam_d20;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;core_apps_sam_ha1;crypto;cryptoauthlib;csp;csp_apps_pic32mz_da;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_ha1;expresslogic_threadx;gfx;gfx_apps;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.4.241\atdf\PIC32MX795F512L.atdf
