files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8E6E4893125920C25696936C33DBF3E4
  logicalPath: config\pic32mx470_curiosity\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8E6E4893125920C25696936C33DBF3E4
- generatedChecksum: B47C99F991BD0A4FF643CE6D253133D9
  logicalPath: config\pic32mx470_curiosity\driver\at25
  name: drv_at25.c
  physicalPath: driver\at25\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B47C99F991BD0A4FF643CE6D253133D9
- generatedChecksum: E520334770AE8B4BD498BDBB000B7086
  logicalPath: config\pic32mx470_curiosity\driver\at25
  name: drv_at25_local.h
  physicalPath: driver\at25\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: E520334770AE8B4BD498BDBB000B7086
- generatedChecksum: EC410AF32A00CC5E9DF0F879297B47F1
  logicalPath: config\pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC410AF32A00CC5E9DF0F879297B47F1
- generatedChecksum: 069214D7287384A60A1C2BAC27714377
  logicalPath: config\pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 069214D7287384A60A1C2BAC27714377
- generatedChecksum: 52CEF89AC4A0C97EA46CD6ADCBA2730F
  logicalPath: config\pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 52CEF89AC4A0C97EA46CD6ADCBA2730F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 6C07CCBE825C68D563EFA8E5F513D46F
  logicalPath: config\pic32mx470_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6C07CCBE825C68D563EFA8E5F513D46F
- generatedChecksum: 745517CBBF6A1DAD59E222176A12D901
  logicalPath: config\pic32mx470_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 745517CBBF6A1DAD59E222176A12D901
- generatedChecksum: EDCDF131C38B3A99E59182BBE969FEEE
  logicalPath: config\pic32mx470_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: EDCDF131C38B3A99E59182BBE969FEEE
- generatedChecksum: B6921E08934407314E0811BFF60E751A
  logicalPath: config\pic32mx470_curiosity\peripheral\spi\spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: B6921E08934407314E0811BFF60E751A
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\pic32mx470_curiosity\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config\pic32mx470_curiosity
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mx470_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 3AD9B94DC2D509696331D0EA0B4CFD37
  logicalPath: config\pic32mx470_curiosity\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3AD9B94DC2D509696331D0EA0B4CFD37
- generatedChecksum: C476E21EF1704A716ED9C519432272E3
  logicalPath: config\pic32mx470_curiosity
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: C476E21EF1704A716ED9C519432272E3
- generatedChecksum: 9D9D50EE197DCDD78072DCC8E9AB2B68
  logicalPath: config\pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D9D50EE197DCDD78072DCC8E9AB2B68
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\pic32mx470_curiosity\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\pic32mx470_curiosity\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: D88B31F2549366FA45428169AED5AA1B
  logicalPath: config\pic32mx470_curiosity\driver\at25
  name: drv_at25.h
  physicalPath: driver\at25
  security: NON_SECURE
  type: HEADER
  userChecksum: D88B31F2549366FA45428169AED5AA1B
- generatedChecksum: 3A5673768ECF05CBFC6F33D688186538
  logicalPath: config\pic32mx470_curiosity\driver\at25
  name: drv_at25_definitions.h
  physicalPath: driver\at25
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A5673768ECF05CBFC6F33D688186538
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mx470_curiosity\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mx470_curiosity\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config\pic32mx470_curiosity\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx470_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config\pic32mx470_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: DF92007BCD881F9C70546028CD0B2220
  logicalPath: config\pic32mx470_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: DF92007BCD881F9C70546028CD0B2220
- generatedChecksum: 8B538ED26B7B1F9177E6F490AAE66B57
  logicalPath: config\pic32mx470_curiosity\peripheral\spi\spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B538ED26B7B1F9177E6F490AAE66B57
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config\pic32mx470_curiosity\peripheral\spi\spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mx470_curiosity\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mx470_curiosity\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mx470_curiosity\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 5F45FB19ABB2D52DE2642941CED1F33F
  logicalPath: config\pic32mx470_curiosity\system\ports
  name: sys_ports.h
  physicalPath: system\ports
  security: NON_SECURE
  type: HEADER
  userChecksum: 5F45FB19ABB2D52DE2642941CED1F33F
- generatedChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
  logicalPath: config\pic32mx470_curiosity\system\ports
  name: sys_ports_mapping.h
  physicalPath: system\ports
  security: NON_SECURE
  type: HEADER
  userChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mx470_curiosity\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mx470_curiosity\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mx470_curiosity\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config\pic32mx470_curiosity
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A26CA65B6345DAB213FD6F3026F7F238
  logicalPath: config\pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: A26CA65B6345DAB213FD6F3026F7F238
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;../src/packs/PIC32MX470F512H_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;../src/packs/PIC32MX470F512H_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
